---
- name: Manage q machines
  hosts: new
  remote_user: root
  tasks:
    - name: Update machine.
      apt:
        name: "*"
        state: latest
      become: yes
    - name: Collet PC minimal info.
      setup:
        gather_subset: 
          - '!min'
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

