---
- name: Creating users in new q machine.
  hosts: new
  remote_user: root
  tasks:
    - name: Update machine.
      apt:
        name: "*"
        state: latest
      become: yes

    - name: Install packages.
      apt:
        pkg:
          - build-essential
          - openssh-server
          - openssh-client
      become: yes

    - name: Clone logq repo.
      git:
        repo: https://github.com/brunopasseti/logq-dotfiles
        dest: /tmp/logq-dotfiles
        clone: yes

    - name: Copying sshd_config file
      copy:
        src: /tmp/logq-dotfiles/sshd_config
        dest: /etc/ssh/sshd_config
      become: yes
        
    - name: Start sshd service, if not started
      service:
        name: sshd.service
        state: started
      become: yes

    # - name: Collet PC minimal info.
    #   setup:
    #     gather_subset: 
    #       - '!min'
    # - name: Print all available facts
    #   ansible.builtin.debug:
    #     var: ansible_facts

